---
- name: "Setting the volume for Windows hosts"
  set_fact: volumes = "{{ windows_hosts.volumes }}"
  when: ansible_system == "Windows"

- name: "Binding the agent ports"
  set_fact: ports = "{{ with_agent.ports }}"
  when: with_agent == True

- name: "Creating the docker volume for data"
  docker_volume:
    name: portainer_data
    state: present

- name: "Starting the Portainer Docker image"
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    detach: True
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
    restart_policy: always
    state: started
