---
- name: "Installing Fail2Ban"
  apt:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: "Starting Fail2Ban service"
  service:
    name: fail2ban
    enabled: yes
    state: started
  when: ansible_os_family == 'Debian'
