---
- name: "Check Ubuntu version supported"
  ansible.builtin.fail:
    msg: "You are trying to install a not supported Debian version ({{ansible_distribution_version}})"
  when: ansible_distribution_major_version|int < 11

- name: "Installing Docker requirements"
  apt:
    name: "{{ debian_packages['docker_requirements'] }}"
    update_cache: yes
    state: present
  when: ansible_distribution_major_version|int >= 11

- name: "Adding the official Docker's GPG key in APT"
  apt_key:
    url: "{{ repository[ansible_distribution]['key'] }}"
    state: present
  when: ansible_distribution_major_version|int >= 11

- name: "Setting the stable Docker's repository"
  apt_repository:
    repo: "{{ repository[ansible_distribution]['name'] }}"
    update_cache: no
    state: present
  when: ansible_distribution_major_version|int >= 11

- name: "Installing Docker packages"
  apt:
    name: "{{ common_packages['docker_packages'] }}"
    update_cache: yes
    state: present
  when: ansible_distribution_major_version|int >= 11

- name: "Installing the Python3 package installer"
  apt:
    name: "{{ debian_packages['docker_python3'] }}"
    state: present
  when: ansible_python.version.major == 3

- name: "Installing the Python package installer"
  apt:
    name: "{{ debian_packages['docker_python'] }}"
    state: present
  when: ansible_python.version.major != 3
