---
- name: "Installing Docker requirements"
  apt:
    name: "{{ debian_packages['docker_requirements'] }}"
    update_cache: yes
    state: present

- name: "Adding the official Docker's GPG key in APT"
  apt_key:
    url: "{{ repository[ansible_distribution]['key'] }}"
    state: present

- name: "Setting the stable Docker's repository"
  apt_repository:
    repo: "{{ repository[ansible_distribution]['name'] }}"
    update_cache: no
    state: present

- name: "Installing Docker packages"
  apt:
    name: "{{ common_packages['docker_packages'] }}"
    update_cache: yes
    state: present

- name: "Installing the Python3 package installer"
  apt:
    name: "{{ debian_packages['docker_python3'] }}"
    state: present
  when: ansible_python.version.major == 3

- name: "Installing the Python package installer"
  apt:
    name: "{{ debian_packages['docker_python'] }}"
    state: present
  when: ansible_python.version.major != 3
